all: floatconverter doubleconverter

floatconverter: floatconverter.c
	g++ -Wall -g -o floatconverter floatconverter.c

doubleconverter: doubleconverter.c
	g++ -Wall -g -o doubleconverter doubleconverter.c

clean:
	rm -f floatconverter
	rm -f doubleconverter
