# Creates docker container using image from privte registry
#
# vault.txt should be stored in Jenkins or Travis!!!
# Required python library by docker_login: pip install docker-py
# ansible-vault --vault-password-file=vault.txt create login
# ansible-playbook containermaker.yml -vvvvv --vault-password-file=vault.txt
#
---
- hosts: localhost
  vars_files:
    - login

  tasks:
    - name: Login into private registry
      docker_login:
        registry: registry.gumartinm.name:443
        username: "{{ docker_login_username }}"
        password: "{{ docker_login_password }}"


# PROMOTION TO DEVELOPMENT ENVIRONMENT:
#
# a) CI server:
# 1. docker build --build-arg artifact_name='backend-mdw--production-schema-0.1.0-SNAPSHOT.jar' --force-rm --rm --tag registry.gumartinm.name:443/backend-mdw--production-schema:0.1.0
#    docker build overrides existing images (I will be using this feature when creating SNAPSHOT versions)
# 2. docker push registry.gumartinm.name:443/backend-mdw--production-schema
#    push to private registry the new tag
# 3. every night, by means of cron script we must clean up our server:
#    docker system prune --all
#
#
# b) DEVELOPMENT ENVIRONMENT server:
# 1. docker rm backend-mdw--production-schema-0.1.0-SNAPSHOT
#    always remove just in case it was already deployed (we are working in this environment with SNAPSHOT versions)
# 2. docker pull registry.gumartinm.name:443/backend-mdw--production-schema:0.1.0-SNAPSHOT
#    we must choose the right version
# 3. docker run --name backend-mdw--production-schema-0.1.0-SNAPSHOT -i -t registry.gumartinm.name:443/backend-mdw--production-schema:0.1.0-SNAPSHOT /bin/bash
#    creating container :)
#
#
